apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: ghcr-external-cluster-secret
spec:
  externalSecretName: "ghcr-external-secret"

  namespaceSelector:
    matchLabels:
      app: custom

  refreshTime: 1h

  externalSecretSpec:
    secretStoreRef:
      name: gitlab-secret-store
      kind: ClusterSecretStore

    refreshInterval: "1h"

    target:
      name: ghcr-secret
      creationPolicy: Owner
      template:
        type: kubernetes.io/dockerconfigjson

        data:
          .dockerconfigjson: |
            {"auths":{"ghcr.io":{"auth":"${{ .GHCR_IO_AUTH_STRING }}"}}}

    data:
      - secretKey: GHCR_IO_AUTH_STRING
        remoteRef:
          key: GHCR_IO_AUTH_STRING
