apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-oauth-external-secret
  namespace: argo-project
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store

  target:
    name: github-oauth-secret
    creationPolicy: Owner

  data:
    - secretKey: clientId
      remoteRef:
        key: ARGOCD_OAUTH_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: ARGOCD_OAUTH_CLIENT_SECRET
