global:
  domain: v2.argocd.haulrest.me

configs:
  params:
    server.insecure: true
  cm:
    url: https://v2.argocd.haulrest.me:9443
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $github-oauth-secret:clientId
          clientSecret: $github-oauth-secret:clientSecret
          orgs:
            - name: BeaverHouse

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: tls-issuer
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls: true
