apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tls-issuer
spec:
  acme:
    email: haulrest@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tls-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
