apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-external-secret-example
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: gitlab-secret-store

  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner

  data:
    - secretKey: api-token
      remoteRef:
        key: CLOUDFLARE_API_KEY
