apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gitlab-secret-store
spec:
  provider:
    # provider type: gitlab
    gitlab:
      # url: https://gitlab.mydomain.com/
      auth:
        SecretRef:
          accessToken:
            namespace: external-secrets
            name: gitlab-secret
            key: token
      projectID: "70159864"
      inheritFromGroups: true
